/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GerenteRouteImport } from './routes/gerente'
import { Route as GameRouteImport } from './routes/game'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as GerenteSaquesRouteImport } from './routes/gerente.saques'
import { Route as GerentePainelRouteImport } from './routes/gerente.painel'
import { Route as GerenteNotificacoesRouteImport } from './routes/gerente.notificacoes'
import { Route as GerenteMeusSaquesRouteImport } from './routes/gerente.meus-saques'
import { Route as GerenteLoginRouteImport } from './routes/gerente.login'
import { Route as GerenteIndicarRouteImport } from './routes/gerente.indicar'
import { Route as GerenteIndicadosRouteImport } from './routes/gerente.indicados'
import { Route as GerenteGerentesRouteImport } from './routes/gerente.gerentes'
import { Route as GerenteCriarDemoRouteImport } from './routes/gerente.criar-demo'
import { Route as GerenteAjustesIndicadosRouteImport } from './routes/gerente.ajustes-indicados'
import { Route as AppSacarRouteImport } from './routes/app.sacar'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppJogarRouteImport } from './routes/app.jogar'
import { Route as AppIndicarRouteImport } from './routes/app.indicar'
import { Route as AppDepositarRouteImport } from './routes/app.depositar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteRoute = GerenteRouteImport.update({
  id: '/gerente',
  path: '/gerente',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const GerenteSaquesRoute = GerenteSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => GerenteRoute,
} as any)
const GerentePainelRoute = GerentePainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteNotificacoesRoute = GerenteNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteMeusSaquesRoute = GerenteMeusSaquesRouteImport.update({
  id: '/meus-saques',
  path: '/meus-saques',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteLoginRoute = GerenteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteIndicarRoute = GerenteIndicarRouteImport.update({
  id: '/indicar',
  path: '/indicar',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteIndicadosRoute = GerenteIndicadosRouteImport.update({
  id: '/indicados',
  path: '/indicados',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteGerentesRoute = GerenteGerentesRouteImport.update({
  id: '/gerentes',
  path: '/gerentes',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteCriarDemoRoute = GerenteCriarDemoRouteImport.update({
  id: '/criar-demo',
  path: '/criar-demo',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteAjustesIndicadosRoute = GerenteAjustesIndicadosRouteImport.update({
  id: '/ajustes-indicados',
  path: '/ajustes-indicados',
  getParentRoute: () => GerenteRoute,
} as any)
const AppSacarRoute = AppSacarRouteImport.update({
  id: '/sacar',
  path: '/sacar',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppJogarRoute = AppJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicarRoute = AppIndicarRouteImport.update({
  id: '/indicar',
  path: '/indicar',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositarRoute = AppDepositarRouteImport.update({
  id: '/depositar',
  path: '/depositar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/gerente': typeof GerenteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/depositar': typeof AppDepositarRoute
  '/app/indicar': typeof AppIndicarRoute
  '/app/jogar': typeof AppJogarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sacar': typeof AppSacarRoute
  '/gerente/ajustes-indicados': typeof GerenteAjustesIndicadosRoute
  '/gerente/criar-demo': typeof GerenteCriarDemoRoute
  '/gerente/gerentes': typeof GerenteGerentesRoute
  '/gerente/indicados': typeof GerenteIndicadosRoute
  '/gerente/indicar': typeof GerenteIndicarRoute
  '/gerente/login': typeof GerenteLoginRoute
  '/gerente/meus-saques': typeof GerenteMeusSaquesRoute
  '/gerente/notificacoes': typeof GerenteNotificacoesRoute
  '/gerente/painel': typeof GerentePainelRoute
  '/gerente/saques': typeof GerenteSaquesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/gerente': typeof GerenteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/depositar': typeof AppDepositarRoute
  '/app/indicar': typeof AppIndicarRoute
  '/app/jogar': typeof AppJogarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sacar': typeof AppSacarRoute
  '/gerente/ajustes-indicados': typeof GerenteAjustesIndicadosRoute
  '/gerente/criar-demo': typeof GerenteCriarDemoRoute
  '/gerente/gerentes': typeof GerenteGerentesRoute
  '/gerente/indicados': typeof GerenteIndicadosRoute
  '/gerente/indicar': typeof GerenteIndicarRoute
  '/gerente/login': typeof GerenteLoginRoute
  '/gerente/meus-saques': typeof GerenteMeusSaquesRoute
  '/gerente/notificacoes': typeof GerenteNotificacoesRoute
  '/gerente/painel': typeof GerentePainelRoute
  '/gerente/saques': typeof GerenteSaquesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/gerente': typeof GerenteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/depositar': typeof AppDepositarRoute
  '/app/indicar': typeof AppIndicarRoute
  '/app/jogar': typeof AppJogarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sacar': typeof AppSacarRoute
  '/gerente/ajustes-indicados': typeof GerenteAjustesIndicadosRoute
  '/gerente/criar-demo': typeof GerenteCriarDemoRoute
  '/gerente/gerentes': typeof GerenteGerentesRoute
  '/gerente/indicados': typeof GerenteIndicadosRoute
  '/gerente/indicar': typeof GerenteIndicarRoute
  '/gerente/login': typeof GerenteLoginRoute
  '/gerente/meus-saques': typeof GerenteMeusSaquesRoute
  '/gerente/notificacoes': typeof GerenteNotificacoesRoute
  '/gerente/painel': typeof GerentePainelRoute
  '/gerente/saques': typeof GerenteSaquesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/game'
    | '/gerente'
    | '/login'
    | '/app/depositar'
    | '/app/indicar'
    | '/app/jogar'
    | '/app/perfil'
    | '/app/sacar'
    | '/gerente/ajustes-indicados'
    | '/gerente/criar-demo'
    | '/gerente/gerentes'
    | '/gerente/indicados'
    | '/gerente/indicar'
    | '/gerente/login'
    | '/gerente/meus-saques'
    | '/gerente/notificacoes'
    | '/gerente/painel'
    | '/gerente/saques'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/game'
    | '/gerente'
    | '/login'
    | '/app/depositar'
    | '/app/indicar'
    | '/app/jogar'
    | '/app/perfil'
    | '/app/sacar'
    | '/gerente/ajustes-indicados'
    | '/gerente/criar-demo'
    | '/gerente/gerentes'
    | '/gerente/indicados'
    | '/gerente/indicar'
    | '/gerente/login'
    | '/gerente/meus-saques'
    | '/gerente/notificacoes'
    | '/gerente/painel'
    | '/gerente/saques'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/game'
    | '/gerente'
    | '/login'
    | '/app/depositar'
    | '/app/indicar'
    | '/app/jogar'
    | '/app/perfil'
    | '/app/sacar'
    | '/gerente/ajustes-indicados'
    | '/gerente/criar-demo'
    | '/gerente/gerentes'
    | '/gerente/indicados'
    | '/gerente/indicar'
    | '/gerente/login'
    | '/gerente/meus-saques'
    | '/gerente/notificacoes'
    | '/gerente/painel'
    | '/gerente/saques'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  GameRoute: typeof GameRoute
  GerenteRoute: typeof GerenteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente': {
      id: '/gerente'
      path: '/gerente'
      fullPath: '/gerente'
      preLoaderRoute: typeof GerenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/gerente/saques': {
      id: '/gerente/saques'
      path: '/saques'
      fullPath: '/gerente/saques'
      preLoaderRoute: typeof GerenteSaquesRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/painel': {
      id: '/gerente/painel'
      path: '/painel'
      fullPath: '/gerente/painel'
      preLoaderRoute: typeof GerentePainelRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/notificacoes': {
      id: '/gerente/notificacoes'
      path: '/notificacoes'
      fullPath: '/gerente/notificacoes'
      preLoaderRoute: typeof GerenteNotificacoesRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/meus-saques': {
      id: '/gerente/meus-saques'
      path: '/meus-saques'
      fullPath: '/gerente/meus-saques'
      preLoaderRoute: typeof GerenteMeusSaquesRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/login': {
      id: '/gerente/login'
      path: '/login'
      fullPath: '/gerente/login'
      preLoaderRoute: typeof GerenteLoginRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/indicar': {
      id: '/gerente/indicar'
      path: '/indicar'
      fullPath: '/gerente/indicar'
      preLoaderRoute: typeof GerenteIndicarRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/indicados': {
      id: '/gerente/indicados'
      path: '/indicados'
      fullPath: '/gerente/indicados'
      preLoaderRoute: typeof GerenteIndicadosRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/gerentes': {
      id: '/gerente/gerentes'
      path: '/gerentes'
      fullPath: '/gerente/gerentes'
      preLoaderRoute: typeof GerenteGerentesRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/criar-demo': {
      id: '/gerente/criar-demo'
      path: '/criar-demo'
      fullPath: '/gerente/criar-demo'
      preLoaderRoute: typeof GerenteCriarDemoRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/ajustes-indicados': {
      id: '/gerente/ajustes-indicados'
      path: '/ajustes-indicados'
      fullPath: '/gerente/ajustes-indicados'
      preLoaderRoute: typeof GerenteAjustesIndicadosRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/app/sacar': {
      id: '/app/sacar'
      path: '/sacar'
      fullPath: '/app/sacar'
      preLoaderRoute: typeof AppSacarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jogar': {
      id: '/app/jogar'
      path: '/jogar'
      fullPath: '/app/jogar'
      preLoaderRoute: typeof AppJogarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/indicar': {
      id: '/app/indicar'
      path: '/indicar'
      fullPath: '/app/indicar'
      preLoaderRoute: typeof AppIndicarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/depositar': {
      id: '/app/depositar'
      path: '/depositar'
      fullPath: '/app/depositar'
      preLoaderRoute: typeof AppDepositarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDepositarRoute: typeof AppDepositarRoute
  AppIndicarRoute: typeof AppIndicarRoute
  AppJogarRoute: typeof AppJogarRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppSacarRoute: typeof AppSacarRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDepositarRoute: AppDepositarRoute,
  AppIndicarRoute: AppIndicarRoute,
  AppJogarRoute: AppJogarRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppSacarRoute: AppSacarRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GerenteRouteChildren {
  GerenteAjustesIndicadosRoute: typeof GerenteAjustesIndicadosRoute
  GerenteCriarDemoRoute: typeof GerenteCriarDemoRoute
  GerenteGerentesRoute: typeof GerenteGerentesRoute
  GerenteIndicadosRoute: typeof GerenteIndicadosRoute
  GerenteIndicarRoute: typeof GerenteIndicarRoute
  GerenteLoginRoute: typeof GerenteLoginRoute
  GerenteMeusSaquesRoute: typeof GerenteMeusSaquesRoute
  GerenteNotificacoesRoute: typeof GerenteNotificacoesRoute
  GerentePainelRoute: typeof GerentePainelRoute
  GerenteSaquesRoute: typeof GerenteSaquesRoute
}

const GerenteRouteChildren: GerenteRouteChildren = {
  GerenteAjustesIndicadosRoute: GerenteAjustesIndicadosRoute,
  GerenteCriarDemoRoute: GerenteCriarDemoRoute,
  GerenteGerentesRoute: GerenteGerentesRoute,
  GerenteIndicadosRoute: GerenteIndicadosRoute,
  GerenteIndicarRoute: GerenteIndicarRoute,
  GerenteLoginRoute: GerenteLoginRoute,
  GerenteMeusSaquesRoute: GerenteMeusSaquesRoute,
  GerenteNotificacoesRoute: GerenteNotificacoesRoute,
  GerentePainelRoute: GerentePainelRoute,
  GerenteSaquesRoute: GerenteSaquesRoute,
}

const GerenteRouteWithChildren =
  GerenteRoute._addFileChildren(GerenteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  GameRoute: GameRoute,
  GerenteRoute: GerenteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
