/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GerenteRouteImport } from './routes/gerente'
import { Route as GameRouteImport } from './routes/game'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as GerenteSaquesRouteImport } from './routes/gerente.saques'
import { Route as GerentePainelRouteImport } from './routes/gerente.painel'
import { Route as GerenteNotificacoesRouteImport } from './routes/gerente.notificacoes'
import { Route as GerenteMeusSaquesRouteImport } from './routes/gerente.meus-saques'
import { Route as GerenteLoginRouteImport } from './routes/gerente.login'
import { Route as GerenteIndicarRouteImport } from './routes/gerente.indicar'
import { Route as GerenteIndicadosRouteImport } from './routes/gerente.indicados'
import { Route as GerenteGerentesRouteImport } from './routes/gerente.gerentes'
import { Route as GerenteCriarDemoRouteImport } from './routes/gerente.criar-demo'
import { Route as GerenteAjustesIndicadosRouteImport } from './routes/gerente.ajustes-indicados'
import { Route as AppSacarRouteImport } from './routes/app.sacar'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppJogarRouteImport } from './routes/app.jogar'
import { Route as AppIndicarRouteImport } from './routes/app.indicar'
import { Route as AppDepositarRouteImport } from './routes/app.depositar'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRiskAlertsRouteImport } from './routes/admin.risk-alerts'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNetworkRouteImport } from './routes/admin.network'
import { Route as AdminManagersRouteImport } from './routes/admin.managers'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHelixRouteImport } from './routes/admin.helix'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAffiliatesRouteImport } from './routes/admin.affiliates'
import { Route as ApiPublicWebhooksDiggionSecretRouteImport } from './routes/api/public/webhooks.diggion.$secret'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteRoute = GerenteRouteImport.update({
  id: '/gerente',
  path: '/gerente',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const GerenteSaquesRoute = GerenteSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => GerenteRoute,
} as any)
const GerentePainelRoute = GerentePainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteNotificacoesRoute = GerenteNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteMeusSaquesRoute = GerenteMeusSaquesRouteImport.update({
  id: '/meus-saques',
  path: '/meus-saques',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteLoginRoute = GerenteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteIndicarRoute = GerenteIndicarRouteImport.update({
  id: '/indicar',
  path: '/indicar',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteIndicadosRoute = GerenteIndicadosRouteImport.update({
  id: '/indicados',
  path: '/indicados',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteGerentesRoute = GerenteGerentesRouteImport.update({
  id: '/gerentes',
  path: '/gerentes',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteCriarDemoRoute = GerenteCriarDemoRouteImport.update({
  id: '/criar-demo',
  path: '/criar-demo',
  getParentRoute: () => GerenteRoute,
} as any)
const GerenteAjustesIndicadosRoute = GerenteAjustesIndicadosRouteImport.update({
  id: '/ajustes-indicados',
  path: '/ajustes-indicados',
  getParentRoute: () => GerenteRoute,
} as any)
const AppSacarRoute = AppSacarRouteImport.update({
  id: '/sacar',
  path: '/sacar',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppJogarRoute = AppJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicarRoute = AppIndicarRouteImport.update({
  id: '/indicar',
  path: '/indicar',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositarRoute = AppDepositarRouteImport.update({
  id: '/depositar',
  path: '/depositar',
  getParentRoute: () => AppRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiskAlertsRoute = AdminRiskAlertsRouteImport.update({
  id: '/risk-alerts',
  path: '/risk-alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNetworkRoute = AdminNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManagersRoute = AdminManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelixRoute = AdminHelixRouteImport.update({
  id: '/helix',
  path: '/helix',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWebhooksDiggionSecretRoute =
  ApiPublicWebhooksDiggionSecretRouteImport.update({
    id: '/api/public/webhooks/diggion/$secret',
    path: '/api/public/webhooks/diggion/$secret',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/gerente': typeof GerenteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/helix': typeof AdminHelixRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/managers': typeof AdminManagersRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/risk-alerts': typeof AdminRiskAlertsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/depositar': typeof AppDepositarRoute
  '/app/indicar': typeof AppIndicarRoute
  '/app/jogar': typeof AppJogarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sacar': typeof AppSacarRoute
  '/gerente/ajustes-indicados': typeof GerenteAjustesIndicadosRoute
  '/gerente/criar-demo': typeof GerenteCriarDemoRoute
  '/gerente/gerentes': typeof GerenteGerentesRoute
  '/gerente/indicados': typeof GerenteIndicadosRoute
  '/gerente/indicar': typeof GerenteIndicarRoute
  '/gerente/login': typeof GerenteLoginRoute
  '/gerente/meus-saques': typeof GerenteMeusSaquesRoute
  '/gerente/notificacoes': typeof GerenteNotificacoesRoute
  '/gerente/painel': typeof GerentePainelRoute
  '/gerente/saques': typeof GerenteSaquesRoute
  '/app/': typeof AppIndexRoute
  '/api/public/webhooks/diggion/$secret': typeof ApiPublicWebhooksDiggionSecretRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/gerente': typeof GerenteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/helix': typeof AdminHelixRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/managers': typeof AdminManagersRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/risk-alerts': typeof AdminRiskAlertsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/depositar': typeof AppDepositarRoute
  '/app/indicar': typeof AppIndicarRoute
  '/app/jogar': typeof AppJogarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sacar': typeof AppSacarRoute
  '/gerente/ajustes-indicados': typeof GerenteAjustesIndicadosRoute
  '/gerente/criar-demo': typeof GerenteCriarDemoRoute
  '/gerente/gerentes': typeof GerenteGerentesRoute
  '/gerente/indicados': typeof GerenteIndicadosRoute
  '/gerente/indicar': typeof GerenteIndicarRoute
  '/gerente/login': typeof GerenteLoginRoute
  '/gerente/meus-saques': typeof GerenteMeusSaquesRoute
  '/gerente/notificacoes': typeof GerenteNotificacoesRoute
  '/gerente/painel': typeof GerentePainelRoute
  '/gerente/saques': typeof GerenteSaquesRoute
  '/app': typeof AppIndexRoute
  '/api/public/webhooks/diggion/$secret': typeof ApiPublicWebhooksDiggionSecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/gerente': typeof GerenteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/helix': typeof AdminHelixRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/managers': typeof AdminManagersRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/risk-alerts': typeof AdminRiskAlertsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/depositar': typeof AppDepositarRoute
  '/app/indicar': typeof AppIndicarRoute
  '/app/jogar': typeof AppJogarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sacar': typeof AppSacarRoute
  '/gerente/ajustes-indicados': typeof GerenteAjustesIndicadosRoute
  '/gerente/criar-demo': typeof GerenteCriarDemoRoute
  '/gerente/gerentes': typeof GerenteGerentesRoute
  '/gerente/indicados': typeof GerenteIndicadosRoute
  '/gerente/indicar': typeof GerenteIndicarRoute
  '/gerente/login': typeof GerenteLoginRoute
  '/gerente/meus-saques': typeof GerenteMeusSaquesRoute
  '/gerente/notificacoes': typeof GerenteNotificacoesRoute
  '/gerente/painel': typeof GerentePainelRoute
  '/gerente/saques': typeof GerenteSaquesRoute
  '/app/': typeof AppIndexRoute
  '/api/public/webhooks/diggion/$secret': typeof ApiPublicWebhooksDiggionSecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/game'
    | '/gerente'
    | '/login'
    | '/admin/affiliates'
    | '/admin/audit-logs'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/finance'
    | '/admin/helix'
    | '/admin/login'
    | '/admin/managers'
    | '/admin/network'
    | '/admin/reports'
    | '/admin/risk-alerts'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/depositar'
    | '/app/indicar'
    | '/app/jogar'
    | '/app/perfil'
    | '/app/sacar'
    | '/gerente/ajustes-indicados'
    | '/gerente/criar-demo'
    | '/gerente/gerentes'
    | '/gerente/indicados'
    | '/gerente/indicar'
    | '/gerente/login'
    | '/gerente/meus-saques'
    | '/gerente/notificacoes'
    | '/gerente/painel'
    | '/gerente/saques'
    | '/app/'
    | '/api/public/webhooks/diggion/$secret'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/game'
    | '/gerente'
    | '/login'
    | '/admin/affiliates'
    | '/admin/audit-logs'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/finance'
    | '/admin/helix'
    | '/admin/login'
    | '/admin/managers'
    | '/admin/network'
    | '/admin/reports'
    | '/admin/risk-alerts'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/depositar'
    | '/app/indicar'
    | '/app/jogar'
    | '/app/perfil'
    | '/app/sacar'
    | '/gerente/ajustes-indicados'
    | '/gerente/criar-demo'
    | '/gerente/gerentes'
    | '/gerente/indicados'
    | '/gerente/indicar'
    | '/gerente/login'
    | '/gerente/meus-saques'
    | '/gerente/notificacoes'
    | '/gerente/painel'
    | '/gerente/saques'
    | '/app'
    | '/api/public/webhooks/diggion/$secret'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/game'
    | '/gerente'
    | '/login'
    | '/admin/affiliates'
    | '/admin/audit-logs'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/finance'
    | '/admin/helix'
    | '/admin/login'
    | '/admin/managers'
    | '/admin/network'
    | '/admin/reports'
    | '/admin/risk-alerts'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/depositar'
    | '/app/indicar'
    | '/app/jogar'
    | '/app/perfil'
    | '/app/sacar'
    | '/gerente/ajustes-indicados'
    | '/gerente/criar-demo'
    | '/gerente/gerentes'
    | '/gerente/indicados'
    | '/gerente/indicar'
    | '/gerente/login'
    | '/gerente/meus-saques'
    | '/gerente/notificacoes'
    | '/gerente/painel'
    | '/gerente/saques'
    | '/app/'
    | '/api/public/webhooks/diggion/$secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  GameRoute: typeof GameRoute
  GerenteRoute: typeof GerenteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicWebhooksDiggionSecretRoute: typeof ApiPublicWebhooksDiggionSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente': {
      id: '/gerente'
      path: '/gerente'
      fullPath: '/gerente'
      preLoaderRoute: typeof GerenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/gerente/saques': {
      id: '/gerente/saques'
      path: '/saques'
      fullPath: '/gerente/saques'
      preLoaderRoute: typeof GerenteSaquesRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/painel': {
      id: '/gerente/painel'
      path: '/painel'
      fullPath: '/gerente/painel'
      preLoaderRoute: typeof GerentePainelRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/notificacoes': {
      id: '/gerente/notificacoes'
      path: '/notificacoes'
      fullPath: '/gerente/notificacoes'
      preLoaderRoute: typeof GerenteNotificacoesRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/meus-saques': {
      id: '/gerente/meus-saques'
      path: '/meus-saques'
      fullPath: '/gerente/meus-saques'
      preLoaderRoute: typeof GerenteMeusSaquesRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/login': {
      id: '/gerente/login'
      path: '/login'
      fullPath: '/gerente/login'
      preLoaderRoute: typeof GerenteLoginRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/indicar': {
      id: '/gerente/indicar'
      path: '/indicar'
      fullPath: '/gerente/indicar'
      preLoaderRoute: typeof GerenteIndicarRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/indicados': {
      id: '/gerente/indicados'
      path: '/indicados'
      fullPath: '/gerente/indicados'
      preLoaderRoute: typeof GerenteIndicadosRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/gerentes': {
      id: '/gerente/gerentes'
      path: '/gerentes'
      fullPath: '/gerente/gerentes'
      preLoaderRoute: typeof GerenteGerentesRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/criar-demo': {
      id: '/gerente/criar-demo'
      path: '/criar-demo'
      fullPath: '/gerente/criar-demo'
      preLoaderRoute: typeof GerenteCriarDemoRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/gerente/ajustes-indicados': {
      id: '/gerente/ajustes-indicados'
      path: '/ajustes-indicados'
      fullPath: '/gerente/ajustes-indicados'
      preLoaderRoute: typeof GerenteAjustesIndicadosRouteImport
      parentRoute: typeof GerenteRoute
    }
    '/app/sacar': {
      id: '/app/sacar'
      path: '/sacar'
      fullPath: '/app/sacar'
      preLoaderRoute: typeof AppSacarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jogar': {
      id: '/app/jogar'
      path: '/jogar'
      fullPath: '/app/jogar'
      preLoaderRoute: typeof AppJogarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/indicar': {
      id: '/app/indicar'
      path: '/indicar'
      fullPath: '/app/indicar'
      preLoaderRoute: typeof AppIndicarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/depositar': {
      id: '/app/depositar'
      path: '/depositar'
      fullPath: '/app/depositar'
      preLoaderRoute: typeof AppDepositarRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/risk-alerts': {
      id: '/admin/risk-alerts'
      path: '/risk-alerts'
      fullPath: '/admin/risk-alerts'
      preLoaderRoute: typeof AdminRiskAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/network': {
      id: '/admin/network'
      path: '/network'
      fullPath: '/admin/network'
      preLoaderRoute: typeof AdminNetworkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/managers': {
      id: '/admin/managers'
      path: '/managers'
      fullPath: '/admin/managers'
      preLoaderRoute: typeof AdminManagersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/helix': {
      id: '/admin/helix'
      path: '/helix'
      fullPath: '/admin/helix'
      preLoaderRoute: typeof AdminHelixRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/webhooks/diggion/$secret': {
      id: '/api/public/webhooks/diggion/$secret'
      path: '/api/public/webhooks/diggion/$secret'
      fullPath: '/api/public/webhooks/diggion/$secret'
      preLoaderRoute: typeof ApiPublicWebhooksDiggionSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminHelixRoute: typeof AdminHelixRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminManagersRoute: typeof AdminManagersRoute
  AdminNetworkRoute: typeof AdminNetworkRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRiskAlertsRoute: typeof AdminRiskAlertsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminHelixRoute: AdminHelixRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminManagersRoute: AdminManagersRoute,
  AdminNetworkRoute: AdminNetworkRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRiskAlertsRoute: AdminRiskAlertsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDepositarRoute: typeof AppDepositarRoute
  AppIndicarRoute: typeof AppIndicarRoute
  AppJogarRoute: typeof AppJogarRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppSacarRoute: typeof AppSacarRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDepositarRoute: AppDepositarRoute,
  AppIndicarRoute: AppIndicarRoute,
  AppJogarRoute: AppJogarRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppSacarRoute: AppSacarRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GerenteRouteChildren {
  GerenteAjustesIndicadosRoute: typeof GerenteAjustesIndicadosRoute
  GerenteCriarDemoRoute: typeof GerenteCriarDemoRoute
  GerenteGerentesRoute: typeof GerenteGerentesRoute
  GerenteIndicadosRoute: typeof GerenteIndicadosRoute
  GerenteIndicarRoute: typeof GerenteIndicarRoute
  GerenteLoginRoute: typeof GerenteLoginRoute
  GerenteMeusSaquesRoute: typeof GerenteMeusSaquesRoute
  GerenteNotificacoesRoute: typeof GerenteNotificacoesRoute
  GerentePainelRoute: typeof GerentePainelRoute
  GerenteSaquesRoute: typeof GerenteSaquesRoute
}

const GerenteRouteChildren: GerenteRouteChildren = {
  GerenteAjustesIndicadosRoute: GerenteAjustesIndicadosRoute,
  GerenteCriarDemoRoute: GerenteCriarDemoRoute,
  GerenteGerentesRoute: GerenteGerentesRoute,
  GerenteIndicadosRoute: GerenteIndicadosRoute,
  GerenteIndicarRoute: GerenteIndicarRoute,
  GerenteLoginRoute: GerenteLoginRoute,
  GerenteMeusSaquesRoute: GerenteMeusSaquesRoute,
  GerenteNotificacoesRoute: GerenteNotificacoesRoute,
  GerentePainelRoute: GerentePainelRoute,
  GerenteSaquesRoute: GerenteSaquesRoute,
}

const GerenteRouteWithChildren =
  GerenteRoute._addFileChildren(GerenteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  GameRoute: GameRoute,
  GerenteRoute: GerenteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicWebhooksDiggionSecretRoute: ApiPublicWebhooksDiggionSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
